### ISSUE TITLE
split the module into different files

### ISSUE THREAD

**Issue by juliaoverflow** [JullianDev/deno-signalr#4]
Easier accessibility & modification, one file is too messy.

Instead of:./src.ts, do:
./src/{file}.ts with files specifically for all types or classes.

**Comment by userterminal** [comment]
What kind of system are you thinking for this?

**Comment by juliaoverflow** [comment]
> What kind of system are you thinking for this?

(just edited top comment) Thinking of `./src/{file}.ts` since it's a lot more standard. Of course there'd be a file specifically for enums, interfaces, etc.

**Comment by juliaoverflow** [comment]
Done in[01641a5962003fa3548e61d67099297d1b5eae12](https://github.com/Julli4n/deno-signalr/commit/01641a5962003fa3548e61d67099297d1b5eae12)
